
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salutation-deployment
spec:
  selector:
    matchLabels:
      app: salutation
  replicas: 2
  template:
    metadata:
      labels:
        app: salutation
    spec:
      containers:
      - name: mukam-salutation
        image: mukam/saluation:latest 